version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - unconvert
    - unparam
    - errorlint
  settings:
    errcheck:
      exclude-functions:
        - os.Remove
        - (io.Closer).Close

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
