version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - unconvert
    - unparam
    - errorlint
    - revive
    - gocritic
    - nilerr
    - misspell
    - gosec
  settings:
    errcheck:
      exclude-functions:
        - os.Remove
        - (io.Closer).Close
    gosec:
      excludes:
        - G304
    revive:
      rules:
        - name: blank-imports
        - name: context-keys-type
        - name: errorf
        - name: if-return
        - name: range
        - name: time-naming
        - name: unreachable-code
        - name: unnecessary-stmt

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
