version: 2

project_name: openrouter-costs-tray

before:
  hooks:
    - go mod tidy

builds:
  - id: openrouter-costs-tray
    main: ./cmd/openrouter-costs-tray
    binary: openrouter-costs-tray
    env:
      - CGO_ENABLED=1
      - CC={{ if eq .Os "windows" }}x86_64-w64-mingw32-gcc{{ else if eq .Arch "arm64" }}aarch64-linux-gnu-gcc{{ else }}gcc{{ end }}
      - CXX={{ if eq .Os "windows" }}x86_64-w64-mingw32-g++{{ else if eq .Arch "arm64" }}aarch64-linux-gnu-g++{{ else }}g++{{ end }}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
